# Generated by Django 3.0.5 on 2020-05-01 15:00

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corona_website_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='daily_confirmed_cases',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(blank=True), size=None), default=[0, 0], size=None),
            preserve_default=False,
        ),
    ]
