# Generated by Django 3.0.5 on 2020-05-01 16:13

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corona_website_app', '0002_country_daily_confirmed_cases'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='daily_confirmed_cases',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=50), size=None), size=None),
        ),
    ]
