# Generated by Django 3.0.5 on 2020-05-01 17:14

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corona_website_app', '0004_auto_20200501_1657'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dates',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dates', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=20, null=True), size=None)),
            ],
        ),
    ]
