# Generated by Django 3.0.5 on 2020-05-01 22:28

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corona_website_app', '0005_dates'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='daily_confirmed_cases',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50, null=True), size=None),
        ),
    ]
