# Generated by Django 3.0.5 on 2020-05-06 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corona_website_app', '0006_auto_20200501_2228'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='country_code',
            field=models.CharField(max_length=3, null=True),
        ),
    ]
